language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
  - "nightly"

sudo: required

# Fetch dependencies
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get install -qq bind9-host
    - pip install -vr requirements.txt

env:
    - TEST_ARGS="--no-network"
    - TEST_ARGS=""

script:
    # Weather and LastFM are hosted in their own repositories and tested separately.
    - supybot-test -c --plugins-dir=. $TEST_ARGS --exclude=./LastFM --exclude=./Weather

notifications:
    email: false

matrix:
    fast_finish: true
    allow_failures:
        - python: "pypy"
        - python: "pypy3"
        - env: TEST_ARGS=""

branches:
  except:
    - /^archive-.*$/
    - /^wip\/.*$/
